version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: proyecto4
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recaudacion_fondos
    ports:
     - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
     - "5000:5000"
    depends_on:
     - db
    environment:
      FLASK_APP: app.py

  frontend:
    build:
      context: ./frontend
    ports:
     - "3000:3000"
    depends_on:
      - backend