version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: proyecto4
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recaudacion_fondos
    ports:
     - "5432:5432"